version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge

    working_directory: ~/rpsec-test-cir

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: database setup
          command: docker-compose run web rails db:create db:migrate
      - run:
          name: run tests
          command: docker-compose run web bundle exec rspec
      - run:
          name: docker-compose down
          command: docker-compose down
